### ISSUE TITLE
How to create project with name other than hello-world, simple, ...?

### ISSUE THREAD

**Issue by jkleiser** [jvasileff/ceylon-dart#2]
I have tried different versions of "ceylon new -name=foo", but I always get this:
```
ceylon new: Argument 'name' to command 'new' should appear at least 1 time(s)
```
I'm looking forward to playing more with Ceylon and Dart. ;-)

**Comment by bjansen** [comment]
`ceylon help new` might help you ;)

The `hello-world` mentioned in the readme is actually a "template" name.

`ceylon new simple --module-name=foo foo` seems to be what you're looking for.

**Comment by jkleiser** [comment]
That seems to work. Thanks!
I think the README should mention this.

**Comment by gavinking** [comment]
It's documented in `ceylon help new`. Does that help?

**Comment by jvasileff** [comment]
Thanks for the feedback @jkleiser. I added a section to the readme for this. Please let me know if you think anything else should be added.
