### ISSUE TITLE
support late+specified values (1.3.2)

### ISSUE THREAD

**Issue by jvasileff** [jvasileff/ceylon-dart#49]
Support 1.3.2 feature https://github.com/ceylon/ceylon/issues/3544

**Comment by jvasileff** [comment]
Done for static and non-static member values, but I guess we need to support top-levels too? Top-levels are already lazy.

**Comment by gavinking** [comment]
`late` is redundant for toplevels, isn't it?

**Comment by jvasileff** [comment]
@gavinking I agree, but there is also the wrinkle that `late` values can be assigned to as an alternate form of initialization.

(side note: the wrinkle has the side effect of eliminating thread safe initialization on the Java backend)

**Comment by jvasileff** [comment]
Closing. Additional initialization checks differed to #39
